version: '3.7'
services:
  service:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    expose:
      - "8000"
    volumes:
      - static_volume:/usr/src/app/static
    env_file:
      - ./app/config/.env
    depends_on:
      - db
      - sqlite3
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./app/sqlscript/movies_schema.sql:/docker-entrypoint-initdb.d/movies_schema.sql
    env_file:
      - ./app/config/.env
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/app/static
    depends_on:
      - service
volumes:
  postgres_data:
  static_volume: